// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cretae_Communication_OneToMany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cretae_Communication_OneToMany));
        
        string IMigrationMetadata.Id
        {
            get { return "201610221452082_Cretae_Communication_OneToMany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
